if(!file.exists("exdata-data-household_power_consumption.zip")) {
  Data <- tempfile()
  download.file("http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",Data)
  data1 <- unzip(Data)
  unlink(Data) }
data <- read.table(data1, header=T, sep=";")
fdata<-subset(data,Date=="1/2/2007"|Date=="2/2/2007")
datetime<-paste(fdata$Date, fdata$Time, format="%d/%m/%Y %H:%M:%S")
DateTime <- as.POSIXct(strptime(datetime,format="%d/%m/%Y %H:%M:%S"))
globalactivepower<-as.numeric(as.character(fdata$Global_active_power))
submetering1<-as.numeric(as.charater(fdata$Sub_metering_1))
submetering1<-as.numeric(as.character(fdata$Sub_metering_1))
submetering2<-as.numeric(as.character(fdata$Sub_metering_2))
submetering3<-as.numeric(as.character(fdata$Sub_metering_3))
png(file="plot4.png")
par(mfrow=c(2,2))
plot(DateTime,Globalactivepower, type="l", xlab="", ylab="Global Active Power")
plot(DateTime,fdata$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(DateTime,submetering1, type="l", xlab="", ylab="Energy sub metering")
lines(DateTime,submetering2,col="red")
lines(DateTime,submetering3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(DateTime,fdata$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
